import { Camera, Review, ReviewData } from './types/index';

export const promoCameraData = {
  id: 7,
  name: 'Look 54',
  previewImg: 'img/content/promo.jpg',
  previewImg2x: 'img/content/promo@2x.jpg',
  previewImgWebp: 'img/content/promo.webp',
  previewImgWebp2x: 'img/content/promo@2x.webp'
};

export const cameraData: Camera = {
  id: 1,
  name: 'Ретрокамера Dus Auge lV',
  vendorCode: 'DA4IU67AD5',
  type: 'Коллекционная',
  category: 'Видеокамера',
  description: 'Немецкий концерн BRW разработал видеокамеру Das Auge IV в начале 80-х годов, однако она до сих пор пользуется популярностью среди коллекционеров и яростных почитателей старинной техники. Вы тоже можете прикоснуться к волшебству аналоговой съёмки, заказав этот чудо-аппарат. Кто знает, может с Das Auge IV начнётся ваш путь к наградам всех престижных кинофестивалей.',
  previewImg: 'img/content/das-auge.jpg',
  level: 'Любительский',
  rating: 4,
  price: 73450,
  previewImg2x: 'img/content/das-auge@2x.jpg',
  previewImgWebp: 'img/content/das-auge.webp',
  previewImgWebp2x: 'img/content/das-auge@2x.webp',
  reviewCount: 8
};

export const camerasList: Camera[] = [
  {
    id: 1,
    name: 'Ретрокамера Dus Auge lV',
    vendorCode: 'DA4IU67AD5',
    type: 'Коллекционная',
    category: 'Видеокамера',
    description: 'Немецкий концерн BRW разработал видеокамеру Das Auge IV в начале 80-х годов, однако она до сих пор пользуется популярностью среди коллекционеров и яростных почитателей старинной техники. Вы тоже можете прикоснуться к волшебству аналоговой съёмки, заказав этот чудо-аппарат. Кто знает, может с Das Auge IV начнётся ваш путь к наградам всех престижных кинофестивалей.',
    previewImg: 'img/content/das-auge.jpg',
    level: 'Любительский',
    rating: 4,
    price: 73450,
    previewImg2x: 'img/content/das-auge@2x.jpg',
    previewImgWebp: 'img/content/das-auge.webp',
    previewImgWebp2x: 'img/content/das-auge@2x.webp',
    reviewCount: 8
  },
  {
    id: 2,
    name: 'FastShot MR-5',
    vendorCode: 'JH34KHN895',
    type: 'Моментальная',
    category: 'Фотоаппарат',
    description: 'Новое слово в создании моментальных фото. Высокое качество снимков, легко перезаряжаемые кассеты, встроенная вспышка. Создавайте альбомы здесь и сейчас.',
    previewImg: 'img/content/fast-shot.jpg',
    level: 'Любительский',
    rating: 3,
    price: 18970,
    previewImg2x: 'img/content/fast-shot@2x.jpg',
    previewImgWebp: 'img/content/fast-shot.webp',
    previewImgWebp2x: 'img/content/fast-shot@2x.webp',
    reviewCount: 9
  },
  {
    id: 3,
    name: 'Instaprinter P2',
    vendorCode: 'KLU789GH56',
    type: 'Цифровая',
    category: 'Фотоаппарат',
    description: 'Компактная модель позволяющая получать чёткие снимки с 25-кратным зумом. В комплекте зарядное устройство и бархатный чехол, а так же удобный шнурок на шею.',
    previewImg: 'img/content/instaprinter.jpg',
    level: 'Нулевой',
    rating: 5,
    price: 8430,
    previewImg2x: 'img/content/instaprinter@2x.jpg',
    previewImgWebp: 'img/content/instaprinter.webp',
    previewImgWebp2x: 'img/content/instaprinter@2x.webp',
    reviewCount: 18
  },
  {
    id: 4,
    name: 'Орлёнок',
    vendorCode: 'O78DFGSD83',
    type: 'Плёночная',
    category: 'Фотоаппарат',
    description: 'Плёночная перезаряжаемая камера нового покаления уже укомплектована плёнкой и оснащена встроенной вспышкой. Легко помещается в руке и обладет интересным дизайном.',
    previewImg: 'img/content/orlenok.jpg',
    level: 'Любительский',
    rating: 3,
    price: 19970,
    previewImg2x: 'img/content/orlenok@2x.jpg',
    previewImgWebp: 'img/content/orlenok.webp',
    previewImgWebp2x: 'img/content/orlenok@2x.webp',
    reviewCount: 1
  },
  {
    id: 5,
    name: 'Van Shot',
    vendorCode: 'YU7RT5GH76',
    type: 'Коллекционная',
    category: 'Видеокамера',
    description: 'Крайне редкое наименование не потеряло актуальность не смотря на сможество альтернатив. После съёмок на данную камеру фильм не стыдно показать в рамках кинофестиваля. Первые 4К настройки, высочайшее разрешение, уникальная цветопередача.',
    previewImg: 'img/content/van-shot.jpg',
    level: 'Профессиональный',
    rating: 5,
    price: 149990,
    previewImg2x: 'img/content/van-shot@2x.jpg',
    previewImgWebp: 'img/content/van-shot.webp',
    previewImgWebp2x: 'img/content/van-shot@2x.webp',
    reviewCount: 12
  },
  {
    id: 6,
    name: 'Click Sap',
    vendorCode: 'KLN54H76F5',
    type: 'Плёночная',
    category: 'Фотоаппарат',
    description: 'Зеркальная камера позволяющая делать четкие фотографии. Вспышка продается и подключается отдельно. Чехол в комплекте. Плёнка 35мм',
    previewImg: 'img/content/click-sap.jpg',
    level: 'Любительский',
    rating: 3,
    price: 9490,
    previewImg2x: 'img/content/click-sap@2x.jpg',
    previewImgWebp: 'img/content/click-sap.webp',
    previewImgWebp2x: 'img/content/click-sap@2x.webp',
    reviewCount: 12
  },
  {
    id: 7,
    name: 'Look 54',
    vendorCode: 'NB54Y',
    type: 'Цифровая',
    category: 'Фотоаппарат',
    description: 'Профессиональный зеркальный фотоаппарат оснащен 56-кратным зумом, позволяет создавать чёткие снимки, а новейший процессор позволяет справляться с шумами и светочувствительностью.',
    previewImg: 'img/content/look-54.jpg',
    level: 'Профессиональный',
    rating: 5,
    price: 96490,
    previewImg2x: 'img/content/look-54@2x.jpg',
    previewImgWebp: 'img/content/look-54.webp',
    previewImgWebp2x: 'img/content/look-54@2x.webp',
    reviewCount: 20
  },
  {
    id: 8,
    name: 'Look SF3',
    vendorCode: 'NBSF3',
    type: 'Цифровая',
    category: 'Фотоаппарат',
    description: 'Идеальная камера для старта в репортажной фотографии. оснащена встроенным стабилизатором и вспышкой. Оптический 15 кратный зум и удобная посадка в руке. ',
    previewImg: 'img/content/look-sf3.jpg',
    level: 'Профессиональный',
    rating: 5,
    price: 63800,
    previewImg2x: 'img/content/look-sf3@2x.jpg',
    previewImgWebp: 'img/content/look-sf3.webp',
    previewImgWebp2x: 'img/content/look-sf3@2x.webp',
    reviewCount: 12
  },
  {
    id: 9,
    name: 'Van60',
    vendorCode: 'YU7RTVA60',
    type: 'Цифровая',
    category: 'Видеокамера',
    description: 'Супер-компактная модель с оптическим зумом проста в управлении и настройка. Отличная первая камера для юных фотографов-исследователей, а яркие расцветки корпуска подчеркнут их индивидуальность.',
    previewImg: 'img/content/van60.jpg',
    level: 'Нулевой',
    rating: 2,
    price: 5690,
    previewImg2x: 'img/content/van60@2x.jpg',
    previewImgWebp: 'img/content/van60.webp',
    previewImgWebp2x: 'img/content/van60@2x.webp',
    reviewCount: 5
  },
  {
    id: 10,
    name: 'Van Click',
    vendorCode: 'YU7RTCV72',
    type: 'Моментальная',
    category: 'Фотоаппарат',
    description: '10-кратный зум, поворотный ЖК-экран, встроенная вспышка, запись видео в двух форматах, следящий автофокус — максимум возможности за лучшую цену.',
    previewImg: 'img/content/van-click.jpg',
    level: 'Любительский',
    rating: 3,
    price: 24590,
    previewImg2x: 'img/content/van-click@2x.jpg',
    previewImgWebp: 'img/content/van-click.webp',
    previewImgWebp2x: 'img/content/van-click@2x.webp',
    reviewCount: 4
  },
  {
    id: 11,
    name: 'SP 520',
    vendorCode: 'JQ756',
    type: 'Коллекционная',
    category: 'Видеокамера',
    description: 'Делайте лучшие фильмы в высоком разрешении. Лёгкая в управлении, мощная начинка, реалистичная цветопередача, возможность просмотра отснятого материала через поворотный ЖК-экран и передача видео через систему Bluetooth.',
    previewImg: 'img/content/sp-520.jpg',
    level: 'Профессиональный',
    rating: 5,
    price: 105590,
    previewImg2x: 'img/content/sp-520@2x.jpg',
    previewImgWebp: 'img/content/sp-520.webp',
    previewImgWebp2x: 'img/content/sp-520@2x.webp',
    reviewCount: 20
  },
  {
    id: 12,
    name: 'Look Shot',
    vendorCode: 'NB569SH',
    type: 'Цифровая',
    category: 'Видеокамера',
    description: 'Гибридный автофокус и динамический стабилизатор по приятной цене. Светочувствительная матрица  без шумов. 8-кратный выездной зум в стильной упаковке.',
    previewImg: 'img/content/look-shot.jpg',
    level: 'Любительский',
    rating: 4,
    price: 18590,
    previewImg2x: 'img/content/look-shot@2x.jpg',
    previewImgWebp: 'img/content/look-shot.webp',
    previewImgWebp2x: 'img/content/look-shot@2x.webp',
    reviewCount: 19
  },
  {
    id: 13,
    name: 'Look Shot 5',
    vendorCode: 'NB569SH5',
    type: 'Плёночная',
    category: 'Фотоаппарат',
    description: 'Аутентичный фотоаппарат для любителей старины. Работает от аккумуляторных батареек. Чехол в комплекте',
    previewImg: 'img/content/look-shot-5.jpg',
    level: 'Нулевой',
    rating: 2,
    price: 4990,
    previewImg2x: 'img/content/look-shot-5@2x.jpg',
    previewImgWebp: 'img/content/look-shot-5.webp',
    previewImgWebp2x: 'img/content/look-shot-5@2x.webp',
    reviewCount: 0
  },
  {
    id: 14,
    name: 'See Shot',
    vendorCode: 'SS56GH',
    type: 'Цифровая',
    category: 'Фотоаппарат',
    description: 'Компактная модель с выездным зумом и скрытой вспышкой. Встроенная стабилизация изображения, можно снимать прямо в движении. Свеочувствительная матрица, передача информации через  Bluetooth. Возможность выстраивать ручные параметры.',
    previewImg: 'img/content/see-shot.jpg',
    level: 'Любительский',
    rating: 3,
    price: 26990,
    previewImg2x: 'img/content/see-shot@2x.jpg',
    previewImgWebp: 'img/content/see-shot.webp',
    previewImgWebp2x: 'img/content/see-shot@2x.webp',
    reviewCount: 6
  },
  {
    id: 15,
    name: 'SS 54F',
    vendorCode: 'SS54FGH',
    type: 'Цифровая',
    category: 'Фотоаппарат',
    description: 'Ручной режим позволяет самостоятельно настраивать параметры съёмки. 20-мегапиксельный сенсор, автофокус и встроенная светокоррекция. Маленькая камера для большихфотовозможностей. ',
    previewImg: 'img/content/ss-54f.jpg',
    level: 'Любительский',
    rating: 4,
    price: 37990,
    previewImg2x: 'img/content/ss-54f@2x.jpg',
    previewImgWebp: 'img/content/ss-54f.webp',
    previewImgWebp2x: 'img/content/ss-54f@2x.webp',
    reviewCount: 2
  },
  {
    id: 16,
    name: 'Small Shot 4',
    vendorCode: 'SS4CFR9',
    type: 'Цифровая',
    category: 'Видеокамера',
    description: 'Для начинающего оператора: познакомьте вашего наблюдателя с его первой камерой. Оптический зум, жк-экран, светочувствительная матрица - стильный кейс для транспортировки. ',
    previewImg: 'img/content/small-shot-4.jpg',
    level: 'Нулевой',
    rating: 1,
    price: 9990,
    previewImg2x: 'img/content/small-shot-4@2x.jpg',
    previewImgWebp: 'img/content/small-shot-4.webp',
    previewImgWebp2x: 'img/content/small-shot-4@2x.webp',
    reviewCount: 16
  },
  {
    id: 17,
    name: 'Look Identify',
    vendorCode: 'LD2000',
    type: 'Коллекционная',
    category: 'Фотоаппарат',
    description: 'Среднеформатная 40-мегапиксельная камера обладет уникальным непоторимым дизайном и ручной росписью корпуса. Ориентирована на студийную съёмку, имеет полный кадр --  35-мм сенсор ',
    previewImg: 'img/content/look-identify.jpg',
    level: 'Любительский',
    rating: 5,
    price: 126000,
    previewImg2x: 'img/content/look-identify@2x.jpg',
    previewImgWebp: 'img/content/look-identify.webp',
    previewImgWebp2x: 'img/content/look-identify@2x.webp',
    reviewCount: 18
  },
  {
    id: 18,
    name: 'LI Shot 76',
    vendorCode: 'LIS76FD',
    type: 'Цифровая',
    category: 'Фотоаппарат',
    description: 'Профессиональная панорамная камера способна создать круговой фото за 20 секунд с помощью  процессора. Новинка на рынке цифровой фотографии -- для неё не нужен штатив или любой другой дополнительный инструмент.',
    previewImg: 'img/content/li-shot-76.jpg',
    level: 'Профессиональный',
    rating: 4,
    price: 94590,
    previewImg2x: 'img/content/li-shot-76@2x.jpg',
    previewImgWebp: 'img/content/li-shot-76.webp',
    previewImgWebp2x: 'img/content/li-shot-76@2x.webp',
    reviewCount: 11
  },
  {
    id: 19,
    name: 'Pro Look 4',
    vendorCode: 'PL4CD',
    type: 'Цифровая',
    category: 'Видеокамера',
    description: 'Камера для любителей запечатлеть каждый момент жизни! Слот для SD-карты и возможность смотреть свои записи сразу на TV.',
    previewImg: 'img/content/pro-look-4.jpg',
    level: 'Любительский',
    rating: 5,
    price: 34590,
    previewImg2x: 'img/content/pro-look-4@2x.jpg',
    previewImgWebp: 'img/content/pro-look-4.webp',
    previewImgWebp2x: 'img/content/pro-look-4@2x.webp',
    reviewCount: 8
  },
  {
    id: 20,
    name: 'Pro Look 56F',
    vendorCode: 'PL67T56F',
    type: 'Цифровая',
    category: 'Видеокамера',
    description: '6-кратный зум, чтобы выделить важные подробности. Простые настройки, ЖК-экран, лёгко помещается в руке - всегда можно брать с собой, Li-Ion аккамулятор.',
    previewImg: 'img/content/pro-look-56f.jpg',
    level: 'Любительский',
    rating: 3,
    price: 27990,
    previewImg2x: 'img/content/pro-look-56f@2x.jpg',
    previewImgWebp: 'img/content/pro-look-56f.webp',
    previewImgWebp2x: 'img/content/pro-look-56f@2x.webp',
    reviewCount: 7
  },
];

export const reviewsList: Review[] = [
  {
    id: '05c2a119-862b-4527-9ba3-95bfe88adf03',
    userName: 'Алексей',
    advantage: 'Хороший стабилизатор и матрица',
    disadvantage: 'Без объектива',
    review: 'Хорошая камера. Лучше за эти деньги не найти.',
    rating: 5,
    createAt: '2022-08-14T21:00:06.102Z',
    cameraId: 1
  },
  {
    id: '9c3b14af-203d-4d85-ae32-1cda613200fe',
    userName: 'Ксения',
    advantage: 'Смущает цена',
    disadvantage: 'Странные звуки при переключении режимов',
    review: 'В целом для домашнего использования в самый раз!',
    rating: 5,
    createAt: '2022-06-19T21:00:06.107Z',
    cameraId: 1
  },
  {
    id: 'd3cb9df5-df0c-4f1e-841c-6e391b5a0b9b',
    userName: 'Ксения',
    advantage: 'Цена соответствует качеству.',
    disadvantage: 'Без объектива',
    review: 'Отличная камера, мне понравилась, пользуюсь около года. Профессионально оценить нет возможности. Есть разные мелкие недочеты, но, по скольку я не являюсь специалисто в данной области, они не ощущаются в моих работах.',
    rating: 4,
    createAt: '2022-06-16T21:00:06.107Z',
    cameraId: 2
  },
  {
    id: 'c54ee06e-db66-485f-86cf-1aebace5fa4a',
    userName: 'Ольга',
    advantage: 'Покупали недавно. Пока нареканий нет.',
    disadvantage: 'Без объектива',
    review: 'Отличная камера, мне понравилась, пользуюсь около года. Профессионально оценить нет возможности. Есть разные мелкие недочеты, но, по скольку я не являюсь специалисто в данной области, они не ощущаются в моих работах.',
    rating: 1,
    createAt: '2022-09-13T21:00:06.107Z',
    cameraId: 2
  },
];

export const reviewData: ReviewData = {
  cameraId: 1,
  userName:'mockUser',
  advantage:'mockAdvantage',
  disadvantage:'mockDisadvantage',
  review:'mockReview',
  rating: 5
};

export const sortedAndFilteredCamerasList: Camera[] = [
  {
    id: 32,
    name: 'Dru pro',
    vendorCode: 'DP89',
    type: 'Моментальная',
    category: 'Фотоаппарат',
    description: 'Одна кнопка отделет вас от запечатления самых ярких эмоций. ',
    previewImg: 'img/content/dru-pro.jpg',
    level: 'Нулевой',
    rating: 3,
    price: 1990,
    previewImg2x: 'img/content/dru-pro@2x.jpg',
    previewImgWebp: 'img/content/dru-pro.webp',
    previewImgWebp2x: 'img/content/dru-pro@2x.webp',
    reviewCount: 14
  },
  {
    id: 13,
    name: 'Look Shot 5',
    vendorCode: 'NB569SH5',
    type: 'Плёночная',
    category: 'Фотоаппарат',
    description: 'Аутентичный фотоаппарат для любителей старины. Работает от аккумуляторных батареек. Чехол в комплекте',
    previewImg: 'img/content/look-shot-5.jpg',
    level: 'Нулевой',
    rating: 2,
    price: 4990,
    previewImg2x: 'img/content/look-shot-5@2x.jpg',
    previewImgWebp: 'img/content/look-shot-5.webp',
    previewImgWebp2x: 'img/content/look-shot-5@2x.webp',
    reviewCount: 20
  },
  {
    id: 9,
    name: 'Van60',
    vendorCode: 'YU7RTVA60',
    type: 'Цифровая',
    category: 'Видеокамера',
    description: 'Супер-компактная модель с оптическим зумом проста в управлении и настройка. Отличная первая камера для юных фотографов-исследователей, а яркие расцветки корпуска подчеркнут их индивидуальность.',
    previewImg: 'img/content/van60.jpg',
    level: 'Нулевой',
    rating: 2,
    price: 5690,
    previewImg2x: 'img/content/van60@2x.jpg',
    previewImgWebp: 'img/content/van60.webp',
    previewImgWebp2x: 'img/content/van60@2x.webp',
    reviewCount: 15
  },
  {
    id: 35,
    name: 'Click Pro',
    vendorCode: 'SSW01',
    type: 'Плёночная',
    category: 'Фотоаппарат',
    description: 'Подходит для дневной съёмки. Интуитивно понятный интерфейс, прочный металический корпус. Подходит для всех форматов плёнок.',
    previewImg: 'img/content/click-pro.jpg',
    level: 'Любительский',
    rating: 3,
    price: 7990,
    previewImg2x: 'img/content/click-pro@2x.jpg',
    previewImgWebp: 'img/content/click-pro.webp',
    previewImgWebp2x: 'img/content/click-pro@2x.webp',
    reviewCount: 6
  },
  {
    id: 3,
    name: 'Instaprinter P2',
    vendorCode: 'KLU789GH56',
    type: 'Цифровая',
    category: 'Фотоаппарат',
    description: 'Компактная модель позволяющая получать чёткие снимки с 25-кратным зумом. В комплекте зарядное устройство и бархатный чехол, а так же удобный шнурок на шею.',
    previewImg: 'img/content/instaprinter.jpg',
    level: 'Нулевой',
    rating: 5,
    price: 8430,
    previewImg2x: 'img/content/instaprinter@2x.jpg',
    previewImgWebp: 'img/content/instaprinter.webp',
    previewImgWebp2x: 'img/content/instaprinter@2x.webp',
    reviewCount: 1
  },
  {
    id: 6,
    name: 'Click Sap',
    vendorCode: 'KLN54H76F5',
    type: 'Плёночная',
    category: 'Фотоаппарат',
    description: 'Зеркальная камера позволяющая делать четкие фотографии. Вспышка продается и подключается отдельно. Чехол в комплекте. Плёнка 35мм',
    previewImg: 'img/content/click-sap.jpg',
    level: 'Любительский',
    rating: 3,
    price: 9490,
    previewImg2x: 'img/content/click-sap@2x.jpg',
    previewImgWebp: 'img/content/click-sap.webp',
    previewImgWebp2x: 'img/content/click-sap@2x.webp',
    reviewCount: 18
  },
  {
    id: 16,
    name: 'Small Shot 4',
    vendorCode: 'SS4CFR9',
    type: 'Цифровая',
    category: 'Видеокамера',
    description: 'Для начинающего оператора: познакомьте вашего наблюдателя с его первой камерой. Оптический зум, жк-экран, светочувствительная матрица - стильный кейс для транспортировки. ',
    previewImg: 'img/content/small-shot-4.jpg',
    level: 'Нулевой',
    rating: 1,
    price: 9990,
    previewImg2x: 'img/content/small-shot-4@2x.jpg',
    previewImgWebp: 'img/content/small-shot-4.webp',
    previewImgWebp2x: 'img/content/small-shot-4@2x.webp',
    reviewCount: 8
  },
  {
    id: 38,
    name: '2000 Go',
    vendorCode: '2000GH',
    type: 'Моментальная',
    category: 'Фотоаппарат',
    description: 'Фотоаппарат для моментальной съёмки со сменными картриджами. Первые 2 упаковки идут в подарок с камерой. Яркий дизайн, лёгкий и крепкий корпус.',
    previewImg: 'img/content/2000-go.jpg',
    level: 'Любительский',
    rating: 1,
    price: 10990,
    previewImg2x: 'img/content/2000-go@2x.jpg',
    previewImgWebp: 'img/content/2000-go.webp',
    previewImgWebp2x: 'img/content/2000-go@2x.webp',
    reviewCount: 4
  },
  {
    id: 23,
    name: 'Go See',
    vendorCode: 'GS45E3',
    type: 'Цифровая',
    category: 'Видеокамера',
    description: 'Каждый момент вашей жизни останется в памяти: простое управление по силам даже ребёнку. Памяти сколько вы пожелаете - свободный слот под SD-карту. Легко подключить к компьютеру или сразу телевизору.',
    previewImg: 'img/content/go-see.jpg',
    level: 'Нулевой',
    rating: 5,
    price: 15990,
    previewImg2x: 'img/content/go-see@2x.jpg',
    previewImgWebp: 'img/content/go-see.webp',
    previewImgWebp2x: 'img/content/go-see@2x.webp',
    reviewCount: 7
  },
  {
    id: 39,
    name: 'Prof g',
    vendorCode: 'PRC56H',
    type: 'Цифровая',
    category: 'Видеокамера',
    description: 'Гибридная система сталибилизации, 12-кратный зум, естественная передача цветов. Ёмкостный аккамулятор - более 30 часов съёмки без подзарядки.',
    previewImg: 'img/content/prof-g.jpg',
    level: 'Любительский',
    rating: 2,
    price: 17990,
    previewImg2x: 'img/content/prof-g@2x.jpg',
    previewImgWebp: 'img/content/prof-g.webp',
    previewImgWebp2x: 'img/content/prof-g@2x.webp',
    reviewCount: 16
  },
  {
    id: 12,
    name: 'Look Shot',
    vendorCode: 'NB569SH',
    type: 'Цифровая',
    category: 'Видеокамера',
    description: 'Гибридный автофокус и динамический стабилизатор по приятной цене. Светочувствительная матрица  без шумов. 8-кратный выездной зум в стильной упаковке.',
    previewImg: 'img/content/look-shot.jpg',
    level: 'Любительский',
    rating: 4,
    price: 18590,
    previewImg2x: 'img/content/look-shot@2x.jpg',
    previewImgWebp: 'img/content/look-shot.webp',
    previewImgWebp2x: 'img/content/look-shot@2x.webp',
    reviewCount: 14
  },
  {
    id: 2,
    name: 'FastShot MR-5',
    vendorCode: 'JH34KHN895',
    type: 'Моментальная',
    category: 'Фотоаппарат',
    description: 'Новое слово в создании моментальных фото. Высокое качество снимков, легко перезаряжаемые кассеты, встроенная вспышка. Создавайте альбомы здесь и сейчас.',
    previewImg: 'img/content/fast-shot.jpg',
    level: 'Любительский',
    rating: 3,
    price: 18970,
    previewImg2x: 'img/content/fast-shot@2x.jpg',
    previewImgWebp: 'img/content/fast-shot.webp',
    previewImgWebp2x: 'img/content/fast-shot@2x.webp',
    reviewCount: 8
  },
  {
    id: 4,
    name: 'Орлёнок',
    vendorCode: 'O78DFGSD83',
    type: 'Плёночная',
    category: 'Фотоаппарат',
    description: 'Плёночная перезаряжаемая камера нового покаления уже укомплектована плёнкой и оснащена встроенной вспышкой. Легко помещается в руке и обладет интересным дизайном.',
    previewImg: 'img/content/orlenok.jpg',
    level: 'Любительский',
    rating: 3,
    price: 19970,
    previewImg2x: 'img/content/orlenok@2x.jpg',
    previewImgWebp: 'img/content/orlenok.webp',
    previewImgWebp2x: 'img/content/orlenok@2x.webp',
    reviewCount: 2
  },
  {
    id: 36,
    name: 'Click Lite R',
    vendorCode: 'SSW45',
    type: 'Цифровая',
    category: 'Видеокамера',
    description: 'Небольшая цифровая камера для съёмок лучших моментов с 16-кратным зумом. Подходит как для ночной, так и для дневной съёмки',
    previewImg: 'img/content/click-lite-r.jpg',
    level: 'Любительский',
    rating: 4,
    price: 19990,
    previewImg2x: 'img/content/click-lite-r@2x.jpg',
    previewImgWebp: 'img/content/click-lite-r.webp',
    previewImgWebp2x: 'img/content/click-lite-r@2x.webp',
    reviewCount: 15
  }
];

export const searchedCameras: Camera[] = [
  {
    id: 5,
    name: 'Van Shot',
    vendorCode: 'YU7RT5GH76',
    type: 'Коллекционная',
    category: 'Видеокамера',
    description: 'Крайне редкое наименование не потеряло актуальность не смотря на сможество альтернатив. После съёмок на данную камеру фильм не стыдно показать в рамках кинофестиваля. Первые 4К настройки, высочайшее разрешение, уникальная цветопередача.',
    previewImg: 'img/content/van-shot.jpg',
    level: 'Профессиональный',
    rating: 5,
    price: 149990,
    previewImg2x: 'img/content/van-shot@2x.jpg',
    previewImgWebp: 'img/content/van-shot.webp',
    previewImgWebp2x: 'img/content/van-shot@2x.webp',
    reviewCount: 7
  },
  {
    id: 9,
    name: 'Van60',
    vendorCode: 'YU7RTVA60',
    type: 'Цифровая',
    category: 'Видеокамера',
    description: 'Супер-компактная модель с оптическим зумом проста в управлении и настройка. Отличная первая камера для юных фотографов-исследователей, а яркие расцветки корпуска подчеркнут их индивидуальность.',
    previewImg: 'img/content/van60.jpg',
    level: 'Нулевой',
    rating: 2,
    price: 5690,
    previewImg2x: 'img/content/van60@2x.jpg',
    previewImgWebp: 'img/content/van60.webp',
    previewImgWebp2x: 'img/content/van60@2x.webp',
    reviewCount: 15
  },
  {
    id: 10,
    name: 'Van Click',
    vendorCode: 'YU7RTCV72',
    type: 'Моментальная',
    category: 'Фотоаппарат',
    description: '10-кратный зум, поворотный ЖК-экран, встроенная вспышка, запись видео в двух форматах, следящий автофокус — максимум возможности за лучшую цену.',
    previewImg: 'img/content/van-click.jpg',
    level: 'Любительский',
    rating: 3,
    price: 24590,
    previewImg2x: 'img/content/van-click@2x.jpg',
    previewImgWebp: 'img/content/van-click.webp',
    previewImgWebp2x: 'img/content/van-click@2x.webp',
    reviewCount: 6
  }
];
